### ISSUE TITLE
➕ [RESOURCE] - <Add SQL playlist>

### ISSUE THREAD

**Issue by AmruthaPariprolu** [jfmartinz/ResourceHub#1284]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
Hi @AmruthaPariprolu. I see that you're actively contribting to this project and I suggests to refrain from creating issue about 'Adding Resource'. IF you want to add resources into a project, you can compile all those resources and make one PR, since GSSOC are strict about spams PRs. Take a look at [this](https://github.com/GSSoC24/Contributor/blob/main/gssoc-guidelines/readme.md). But you can still contribute to other areas, you can learn more about that in the CONTRIBUTING.md
