### ISSUE TITLE
➕ [RESOURCE] - FLUTTER Developer Roadmap

### ISSUE THREAD

**Issue by ThisIsSahaj** [jfmartinz/ResourceHub#1289]
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

App Development | Roadmap

### Provide the URLs of the resources you are adding

[Flutter Roadmap](https://roadmap.sh/flutter)

### Additional Context

![image](https://github.com/jfmartinz/ResourceHub/assets/118066299/289a8816-2b01-4182-8b17-c4d529baa20b)

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

**Comment by jfmartinz** [comment]
Hi @ThisIsSahaj  I see that you're actively contribting to this project and I suggests to refrain from creating issue especially about 'Adding new Resource'. IF you want to add resources into a project, you can compile all those resources and make one PR, since GSSOC are strict about spams PRs. Take a look at [this](https://github.com/GSSoC24/Contributor/blob/main/gssoc-guidelines/readme.md). But you can still contribute to other areas, you can learn more about that in the CONTRIBUTING.md
