### ISSUE TITLE
💡 [FEATURE] - Add "C++ Programming Language" Complete Resources 

### ISSUE THREAD

**Issue by MastanSayyad** [jfmartinz/ResourceHub#333]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hi @jfmartinz
I would like to add Complete resources for C++ Programming Language it would be a great addition to the ResourceHub project.

### Explain your solution

I propose adding a dedicated cpp.md file for Compete C++ Language:

- Roadmap
- Basic Syntax and Structure 
- Object-Oriented Programming (OOP) in C++
- Functions
- Advanced C++ Features
- Advanced OOP Concepts
- Standard Template Library (STL)
- Concurrency and Memory Management
- Modern C++ (C++11 and Beyond)
- Project Ideas (Beginner, Intermediate, Advanced)
- Certification Cources.
- Etc

### Any alternative approaches/features

I'll try to cover all existing topics related to cpp

### Additional Context

Thank you. for the opportunity to contribute with you, Please assign this issue to me under GSSoC 24.

**Comment by jfmartinz** [comment]
Hey @MastanSayyad, you can automatically create PR so It will help me to lessen the time of assigning people. Thanks. Next time. Another thing I made a mistake earlier when I merged your PR but we are trying to solve it already. The structure should be like this:

/Programming Languages
  /Java
  readme.md
 /Javascript
  readme.md

Programming languages is a parent folder and its children is the languages, and each languages has its own readme.md file. This is because to fetch it easily and work perfectly in the wbesite, thanks

**Comment by jfmartinz** [comment]
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/59100a7a-ac80-40ab-ad92-588ad27fdbc6)

**Comment by MastanSayyad** [comment]
Oka, I got all the instructions clearly @jfmartinz

**Comment by jfmartinz** [comment]
Thanks

**Comment by MastanSayyad** [comment]
hey @jfmartinz, as you said that i don't have to raised the issues and can directly pull requests for each programming languages. so I request you to do not assign the issues related to programming languages to others as I am already assign to work on them.

**Comment by jfmartinz** [comment]
Sure, no problem.

**Comment by jfmartinz** [comment]
My bad. Maybe I assigned someone.

**Comment by jfmartinz** [comment]
someone raised issues about c and typescript\ but I closed it already, you can have it all the issues loll gg
