### ISSUE TITLE
💡 [FEATURE] - Resources for Cloud Computing

### ISSUE THREAD

**Issue by chaanakyaaM** [jfmartinz/ResourceHub#358]
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Along with all the other technologies, Cloud computing also a main category in the technology, even the GitHub is a cloud based platform.

### Explain your solution

I would like to add the Resources for cloud computing.

**Comment by Kumar-Ankit56** [comment]
@jfmartinz please guide for this issue we will have create a new folder of cloud computing isn't ?

@chaanakyaaM we will assign this issue shortly 😊

Cheers

**Comment by chaanakyaaM** [comment]
Thank you.

**Comment by jfmartinz** [comment]
I think, no for now. Since currently there a still a lot of category that are incomplete and have a lot of improvements. Maybe soon, but for now, no. 

Current categories in the project are still need improvements like consistency in programming, lack of description in each tablle/section, lack of resources or section in each category. I need to address this first before we add category again.

**Comment by chaanakyaaM** [comment]
ok, sure.
