### ISSUE TITLE
🐞 [BUG] -Alignement of Searched Courses

### ISSUE THREAD

**Issue by Yashgabani845** [jfmartinz/ResourceHub#556]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

whenever we search any course in searchbar then it render those courser and show it
but it does not show us in order
but show randomly(on it's original position )

### let me share picture so it will be more clear to you

![Screenshot (180)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/127788321/fde451f3-3951-4c68-94a7-8b45ab84dba1)

we have to fix this beacuse it is not looking userfriendly
we should set them in one order

### Expected behavior

All searchinf suggest should be4 dynamically in perfect order 
courses should follow the grid

### Steps to reproduce

change the logic of displaying search suggestion
we can do one thing
instead of changing display property of course we can filter and show them 

### Additional Context

this issue is of medium priority 
it should be resolved to enhance the view of website

**Comment by Yashgabani845** [comment]
@jfmartinz please assign me this isssue

**Comment by KomalSrivastava** [comment]
@jfmartinz Issue: Search results are not displayed in a consistent order
One approach to fix this issue is to modify the logic responsible for displaying the search suggestions. Instead of directly displaying the courses as they are retrieved from the backend, we can apply sorting or filtering to ensure that they are displayed in the desired order. For example, you can sort the courses alphabetically by their names before displaying them as search suggestions.

To implement this fix, you'll need to identify the part of the codebase responsible for fetching and displaying the search suggestions. Once you've located this code, you can modify it to include the necessary sorting or filtering logic to ensure that the suggestions are displayed in the correct order.

By addressing this issue, we can improve the user experience of the website by providing search suggestions that are consistently displayed and easier to navigate. If you'd like to assign this task to me, I'll be happy to work on it and implement the necessary changes to resolve the bug.

**Comment by Yashgabani845** [comment]
Yes I am working on it
